## Libraries

In [33]:
import pandas as pd

## Paths

In [34]:
path_data='./src/data_basilics/'
name_file_lieux_equipements_culturels = 'base-des-lieux-et-des-equipements-culturels.csv'
name_file_cinema = 'data_cinema/exploitation - liste des établissements actifs -.xlsx'

## Load data

In [35]:
# culturels
df_culturels=pd.read_csv(path_data+name_file_lieux_equipements_culturels, sep=';', on_bad_lines='skip' ,encoding='utf-8',low_memory=False)
df_culturels.head()

Source  \
0  Ministère de la Culture - Service du livre et ...   
1  Ministère de la Culture - Service du livre et ...   
2  Ministère de la Culture - Service du livre et ...   
3  Ministère de la Culture - Service du livre et ...   
4  Ministère de la Culture - Service du livre et ...   

                                           Nom                  Adresse  \
0                    Médiathèque de COMMENSACQ   200  ROUTE DE TRENSACQ   
1  Bibliothèque MUNICIPALE de CREON-D'ARMAGNAC  12, Rue Raoul Follereau   
2                       Bibliothèque de GELOUX    2  PLACE DE LA MAIRIE   
3         Médiathèque CHALOSSE TURSAN HAGETMAU          4 PLACE GRAMONT   
4                          Médiathèque de HINX         100 ROUTE DE DAX   

  Complement Adresse  Code Postal libelle_geographique code_insee  \
0                NaN      40210.0           Commensacq      40085   
1                NaN      40240.0     Créon-d'Armagnac      40087   
2                NaN      40090.0               Geloux      40111   
3                NaN      40700.0             Hagetmau      40119   
4                NaN      40180.0                 Hinx      40126   

  Code Insee Arrondt Identifiant origine Type équipement ou lieu  ...  \
0                402             LI14040            Bibliothèque  ...   
1                402              LI7880            Bibliothèque  ...   
2                402              LI7888            Bibliothèque  ...   
3                402              LI1734            Bibliothèque  ...   
4                401              LI7894            Bibliothèque  ...   

  Annee_Label_Appellation          Latitude           Longitude  \
0                     NaN  44.2106959785251  -0.822884754184157   
1                     NaN   43.993868098598  -0.105588386166206   
2                     NaN  43.9810194468607  -0.638822931528512   
3                     NaN  43.6573228675739  -0.593452338732522   
4                     NaN   43.701671909797  -0.927995381193468   

  Demographie_AP            Demographie_detail_entree  \
0          Actif  historiquement dans la base en 2020   
1          Actif  historiquement dans la base en 2020   
2          Actif  historiquement dans la base en 2020   
3          Actif  historiquement dans la base en 2020   
4          Actif  historiquement dans la base en 2020   

  Démographie_detail_sortie Multi_equipements identifiant_QPV_24  \
0                       NaN               NaN                NaN   
1                       NaN               NaN                NaN   
2                       NaN               NaN                NaN   
3                       NaN               NaN                NaN   
4                       NaN               NaN                NaN   

  identifiant_QPV_15                       coordonnees_geo  
0                NaN  44.2106959785251, -0.822884754184157  
1                NaN   43.993868098598, -0.105588386166206  
2                NaN  43.9810194468607, -0.638822931528512  
3                NaN  43.6573228675739, -0.593452338732522  
4                NaN   43.701671909797, -0.927995381193468  

[5 rows x 54 columns]

In [36]:
df_culturels.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73791 entries, 0 to 73790
Data columns (total 54 columns):
 #   Column                                   Non-Null Count  Dtype  
---  ------                                   --------------  -----  
 0   Source                                   73760 non-null  object 
 1   Nom                                      73791 non-null  object 
 2   Adresse                                  43422 non-null  object 
 3   Complement Adresse                       335 non-null    object 
 4   Code Postal                              72851 non-null  float64
 5   libelle_geographique                     73774 non-null  object 
 6   code_insee                               73791 non-null  object 
 7   Code Insee Arrondt                       73684 non-null  object 
 8   Identifiant origine                      67814 non-null  object 
 9   Type équipement ou lieu                  73791 non-null  object 
 10  Label et appellation                     53952

In [37]:
df_culturels.columns

Index(['Source', 'Nom', 'Adresse', 'Complement Adresse', 'Code Postal',
       'libelle_geographique', 'code_insee', 'Code Insee Arrondt',
       'Identifiant origine', 'Type équipement ou lieu',
       'Label et appellation', 'Région', 'Domaine', 'Sous-domaine',
       'Archéologie détail', 'Adresse postale', 'Département',
       'Précision équipement', 'N_Département', 'N_Région', 'Fonction_1',
       'Fonction_2', 'Fonction_3', 'Fonction_4', 'Multiplexe',
       'Type_de_cinema', 'Nombre_fauteuils_de_cinema', 'Nombre_ecrans',
       'Nombre_de_salles_de_theatre', 'Organisme_Siège_du_theatre',
       'Jauge_du_theatre', 'Code_du_reseau_de_Bibliothèques',
       'Nom_du_Réseau_de_Bibliothèques', 'Nom_de_l'Illustre',
       'Surface_Bibliothèque', 'Rang', 'Ident',
       'Identifiant_deps_à_partir_de_2022', 'Libelle_EPCI', 'Code_Insee_EPCI',
       'Identifiant_deps_old', 'Précision protection sites et monuments',
       'GCD', 'AAV', 'Annee_Label_Appellation', 'Latitude', 'Longitude'

## Exploration de données

### code_insee vs code postale versus libeles géographique

In [38]:
nbr_libelles_geographiques = len(df_culturels['libelle_geographique'].unique())
nbr_libelles_geographiques

21278

In [39]:
df_culturels['libelle_geographique'].unique()

array(['Commensacq', "Créon-d'Armagnac", 'Geloux', ..., 'Canala',
       'Koumac', 'Pouébo'], dtype=object)

In [40]:
nbr_code_postal = len(df_culturels['Code Postal'].unique())
nbr_code_postal

6037

In [41]:
df_culturels['code_insee'].unique()

array(['40085', '40087', '40111', ..., '98804', '98812', '98824'],
      dtype=object)

In [42]:
nbr_code_insee = len(df_culturels['code_insee'].unique())
nbr_code_insee

22288

In [43]:
nbr_code_insee_EPCI = len(df_culturels['Code_Insee_EPCI'].unique())
nbr_code_insee_EPCI 

1256

In [44]:
nbr_code_insee_Arrondt = len(df_culturels['Code Insee Arrondt'].unique())
nbr_code_insee_Arrondt

334

In [45]:
df_culturels['Code Insee Arrondt'].unique()

array(['402', '401', '413', '411', '412', '9731', '422', '421', '423',
       '593', '432', '433', '431', '445', '443', '442', '596', '451',
       '453', '452', '594', '461', '462', '463', '471', '474', '473',
       '472', '595', '482', '481', '591', '491', '493', '492', '494',
       '501', '502', '504', '503', '512', '511', '513', '514', '523',
       '521', '522', '531', '533', '532', '544', '543', '541', '542',
       '601', '604', '553', '551', '552', '563', '561', '562', '579',
       '573', '575', '577', '621', '576', '627', '584', '583', '582',
       '581', '592', '623', '622', '912', '602', '603', '922', '613',
       '612', '611', '625', '626', '772', '624', '773', '775', '634',
       '635', '633', '632', '631', '643', '931', '641', '642', '651',
       '652', '653', '663', '662', '661', '674', '673', '675', '678',
       '672', '684', '682', '686', '692', '691', '701', '702', '712',
       '711', '714', '713', '715', '723', '933', '722', '721', '732',
       '731', '932'

### types d'équipements

In [46]:
nbr_type_equipment = len(df_culturels['Type équipement ou lieu'].unique())
nbr_type_equipment

19

In [47]:
type_equipement = df_culturels['Type équipement ou lieu'].unique()
type_equipement

array(['Bibliothèque', "Centre d'art", 'Centre de création artistique',
       'Cinéma', "Service d'archives", 'Monument', 'Lieu archéologique',
       'Centre de création musicale', 'Théâtre', 'Conservatoire',
       "Établissement d'enseignement supérieur", 'Parc et jardin',
       'Librairie', 'Lieu de mémoire', 'Musée', 'Opéra',
       'Centre culturel', 'Scène', 'Espace protégé'], dtype=object)

In [48]:
df_culturels['Type_de_cinema'].unique()

array([nan, 'Fixe', 'Itinérant', 'FIXE'], dtype=object)

In [49]:
df_culturels['Nombre_fauteuils_de_cinema'].unique()

array([  nan,  595., 1938.,  131.,  479.,  110.,  142.,  160.,  436.,
        124.,  600.,  208.,  641.,  112.,  225.,  270.,  388.,  185.,
        244.,  195., 1728.,  176.,   80.,  177.,  377., 1108.,  149.,
        251.,  250.,  120.,  281.,  525.,  905.,  350.,  165.,  285.,
        200.,  450.,  336., 1830.,  451.,  199., 1258.,  164.,  239.,
        231.,  579.,  135.,  392.,  295., 3507.,  155.,  380.,  190.,
        472.,  220.,  806.,  477.,  308.,  111.,  536., 2452.,  178.,
        962.,  354.,  154., 1024.,  174.,  210.,  163.,  358.,  197.,
        167.,   50.,  148.,  227.,  104.,  695.,  141., 1802.,  228.,
       1330.,  212.,  627., 2343.,  407.,  268., 1544.,  516.,  892.,
        215.,  194.,  801.,  364.,   97.,  237.,  331.,  300.,  432.,
        400.,  299.,  188.,  206., 1041.,  835.,   88.,  181.,  374.,
        408.,  553.,  196.,  248.,  544.,  480.,  767.,  150.,  287.,
       1375., 3167.,  230.,  166., 2458.,  144., 1067.,  481., 1961.,
        183.,  249.,

In [50]:
df_culturels['Nombre_ecrans'].unique()

array([nan,  3.,  9.,  1.,  2., 10.,  7.,  4.,  6., 17.,  5., 12.,  8.,
       15., 13., 14., 22., 27., 11., 16., 18., 19., 23.])

In [51]:
df_culturels['Nombre_de_salles_de_theatre'].unique()

array([nan,  1.,  2.,  3.,  4.,  5.])

In [52]:
df_culturels['Organisme_Siège_du_theatre'].unique()

array([nan, 'Théâtre en Miettes', 'Théâtre de Nîmes',
       'Hectare - Scène conventionnée de Vendôme', 'Soufflerie',
       'Théâtre Municipal de Coutances',
       'Maison de la Culture de Bourges',
       'Empreinte - Scène nationale Brive-Tulle',
       '2 Scènes - Scène nationale de Besançon', 'MA Scène nationale',
       'Scènes du Jura', 'Carré - Scène nationale de Château-Gontier',
       'Manège de Maubeuge', 'TANDEM Douai-Arras',
       'Scène nationale du Sud Aquitain',
       "Scène nationale de l'Essonne, Agora-Desnos",
       'Virgule, Centre Transfrontalier de Création Théâtrale',
       'Bords de Scènes', 'Espace des Franciscaines',
       'Service culturel de Morteau', 'Romans Scènes',
       'Service culturel de Châteaudun', 'Salle Pierre-Mendès-France',
       'Théâtre Jean Marmignon', 'Service culturel de Lespinasse',
       "Direction de l'Animation Socioculturelle de la Mairie de Toulouse",
       "Service culturel d'Eysines", 'Théâtres de Saint-Malo',
       'Th

In [53]:
(df_culturels.loc[df_culturels['Type équipement ou lieu']=='Bibliothèque','Nombre_de_salles_de_theatre']).isna().sum()

np.int64(16469)

In [54]:
len(df_culturels.loc[df_culturels['Type équipement ou lieu']=='Bibliothèque','Nombre_de_salles_de_theatre'])

16469

#### rajout d'une colonne catégorie

In [55]:
def assign_categorie(type_equipement):
    if type_equipement in ['Bibliothèque', "Centre d'art", 'Centre de création artistique','théatre', 'cinéma','Centre de création musicale', 'Théâtre', 'Conservatoire','Parc et jardin','Librairie', 'Lieu de mémoire', 'Musée', 'Opéra',"Centre culturel", "Scène", "Espace protégé"]:
        return ('vivant')
    elif type_equipement in ["Service d'archives", 'Monument']:
        return ('patrimoine')
    elif type_equipement ==  "Établissement d'enseignement supérieur":
        return ('Strange')
    else:
        return None  # Si un monument ne correspond à aucune catégorie

In [56]:
# Appliquer la fonction à la colonne 'monument'
df_culturels['categorie'] = df_culturels['Type équipement ou lieu'].apply(assign_categorie)
df_culturels.head()

Source  \
0  Ministère de la Culture - Service du livre et ...   
1  Ministère de la Culture - Service du livre et ...   
2  Ministère de la Culture - Service du livre et ...   
3  Ministère de la Culture - Service du livre et ...   
4  Ministère de la Culture - Service du livre et ...   

                                           Nom                  Adresse  \
0                    Médiathèque de COMMENSACQ   200  ROUTE DE TRENSACQ   
1  Bibliothèque MUNICIPALE de CREON-D'ARMAGNAC  12, Rue Raoul Follereau   
2                       Bibliothèque de GELOUX    2  PLACE DE LA MAIRIE   
3         Médiathèque CHALOSSE TURSAN HAGETMAU          4 PLACE GRAMONT   
4                          Médiathèque de HINX         100 ROUTE DE DAX   

  Complement Adresse  Code Postal libelle_geographique code_insee  \
0                NaN      40210.0           Commensacq      40085   
1                NaN      40240.0     Créon-d'Armagnac      40087   
2                NaN      40090.0               Geloux      40111   
3                NaN      40700.0             Hagetmau      40119   
4                NaN      40180.0                 Hinx      40126   

  Code Insee Arrondt Identifiant origine Type équipement ou lieu  ...  \
0                402             LI14040            Bibliothèque  ...   
1                402              LI7880            Bibliothèque  ...   
2                402              LI7888            Bibliothèque  ...   
3                402              LI1734            Bibliothèque  ...   
4                401              LI7894            Bibliothèque  ...   

           Latitude           Longitude Demographie_AP  \
0  44.2106959785251  -0.822884754184157          Actif   
1   43.993868098598  -0.105588386166206          Actif   
2  43.9810194468607  -0.638822931528512          Actif   
3  43.6573228675739  -0.593452338732522          Actif   
4   43.701671909797  -0.927995381193468          Actif   

             Demographie_detail_entree Démographie_detail_sortie  \
0  historiquement dans la base en 2020                       NaN   
1  historiquement dans la base en 2020                       NaN   
2  historiquement dans la base en 2020                       NaN   
3  historiquement dans la base en 2020                       NaN   
4  historiquement dans la base en 2020                       NaN   

  Multi_equipements identifiant_QPV_24 identifiant_QPV_15  \
0               NaN                NaN                NaN   
1               NaN                NaN                NaN   
2               NaN                NaN                NaN   
3               NaN                NaN                NaN   
4               NaN                NaN                NaN   

                        coordonnees_geo  categorie  
0  44.2106959785251, -0.822884754184157     vivant  
1   43.993868098598, -0.105588386166206     vivant  
2  43.9810194468607, -0.638822931528512     vivant  
3  43.6573228675739, -0.593452338732522     vivant  
4   43.701671909797, -0.927995381193468     vivant  

[5 rows x 55 columns]

### paramètres utiles

In [57]:
param_utiles=['Nom','Adresse','Code Postal','code_insee','libelle_geographique','Type équipement ou lieu','categorie','Latitude','Longitude']
param_utiles

['Nom',
 'Adresse',
 'Code Postal',
 'code_insee',
 'libelle_geographique',
 'Type équipement ou lieu',
 'categorie',
 'Latitude',
 'Longitude']

In [58]:
df_culturels_extracted = df_culturels.loc[:,param_utiles]
df_culturels_extracted.head()

Nom                  Adresse  \
0                    Médiathèque de COMMENSACQ   200  ROUTE DE TRENSACQ   
1  Bibliothèque MUNICIPALE de CREON-D'ARMAGNAC  12, Rue Raoul Follereau   
2                       Bibliothèque de GELOUX    2  PLACE DE LA MAIRIE   
3         Médiathèque CHALOSSE TURSAN HAGETMAU          4 PLACE GRAMONT   
4                          Médiathèque de HINX         100 ROUTE DE DAX   

   Code Postal code_insee libelle_geographique Type équipement ou lieu  \
0      40210.0      40085           Commensacq            Bibliothèque   
1      40240.0      40087     Créon-d'Armagnac            Bibliothèque   
2      40090.0      40111               Geloux            Bibliothèque   
3      40700.0      40119             Hagetmau            Bibliothèque   
4      40180.0      40126                 Hinx            Bibliothèque   

  categorie          Latitude           Longitude  
0    vivant  44.2106959785251  -0.822884754184157  
1    vivant   43.993868098598  -0.105588386166206  
2    vivant  43.9810194468607  -0.638822931528512  
3    vivant  43.6573228675739  -0.593452338732522  
4    vivant   43.701671909797  -0.927995381193468

In [59]:
df_culturels_extracted.groupby('code_insee')

In [69]:
# Regroupement par 'code_postal' et 'categorie', puis comptage des éléments
df_nbre_categorie_parcommune = df_culturels_extracted.groupby(['code_insee', 'categorie']).size().reset_index(name='count')
df_nbre_categorie_parcommune

code_insee   categorie  count
0          01001  patrimoine      1
1          01004  patrimoine      4
2          01004      vivant      1
3          01005  patrimoine      1
4          01005      vivant      1
...          ...         ...    ...
31523      98824      vivant      1
31524      98829      vivant      1
31525      98831      vivant      1
31526      98832      vivant      1
31527      99999      vivant      6

[31528 rows x 3 columns]

In [61]:
df_nbre_categorie_parcommune.to_csv(path_data+'nbre_categorie_parcommune.csv', sep='\t', index=False)  # Save as a tab

In [62]:
# Regroupement par 'code_postal' et 'type equipement', puis comptage des éléments
df_nbre_typequip_parcommune = df_culturels_extracted.groupby(['code_insee', 'Type équipement ou lieu']).size().reset_index(name='count')
df_nbre_typequip_parcommune

code_insee Type équipement ou lieu  count
0          01001                Monument      1
1          01004            Bibliothèque      1
2          01004                  Cinéma      1
3          01004                Monument      3
4          01004      Service d'archives      1
...          ...                     ...    ...
38403      98829            Bibliothèque      1
38404      98831            Bibliothèque      1
38405      98832            Bibliothèque      1
38406      99999         Lieu de mémoire      5
38407      99999                   Musée      1

[38408 rows x 3 columns]

In [63]:
df_nbre_typequip_parcommune.to_csv(path_data+'nbre_typequip_parcommune.csv', sep='\t', index=False)  # Save as a tab

In [68]:
# Ajouter la colonne Code postal, en utilisant 'transform' pour ne pas perdre l'information
df_culturels_extracted['Code postal'] = df_culturels_extracted.groupby('code_insee')['Code Postal'].transform('first')

# Regrouper par Code commune et Catégorie, puis compter les éléments
grouped = df_culturels_extracted.groupby(['Code postal', 'code_insee', 'categorie']).size().reset_index(name='Nombre d\'éléments')

# Afficher le résultat final
print(grouped)


       Code postal code_insee   categorie  Nombre d'éléments
0           1000.0      01053  patrimoine                 38
1           1000.0      01053      vivant                 12
2           1000.0      01344      vivant                  1
3           1090.0      01165  patrimoine                  1
4           1090.0      01169  patrimoine                  1
...            ...        ...         ...                ...
31499      98880.0      98813      vivant                  1
31500      98884.0      98814      vivant                  1
31501      98890.0      98821  patrimoine                  1
31502      98890.0      98821      vivant                  1
31503      99999.0      99999      vivant                  6

[31504 rows x 4 columns]


In [64]:
path_data

'./src/data_basilics/'

uv faut peut etre pas nommer lenvironnement virtuel

on voit pas t'environnelment (car il est ignoré, il est dans gitignore)
mais on a la recette pour le creer grace à toml